- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: import bastion host variables
      include_vars: vars/vpc_setup

    - name: import VPC setup variables
      include_vars: vars/output_vars

    - name: create a new ec2 key pair, returns generated private key
      amazon.aws.ec2_key:
        name: bastion_keypair
        region: "{{region}}"
      register: key_out

    - name: save private key into bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: security group for bastion host
      amazon.aws.ec2_group:
        name: Bastion-host-sg
        description: sg with rule descriptions
        vpc_id: "{{ vpcid }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
            rule_desc: allow MY ip on port 22
      register: bastionSG_out

    - name: start bastion instance
      ec2:
        key_name: bastion_keypair
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        region: "{{region}}"
        wait: yes
        wait_timeout: 300
        vpc_subnet_id: "{{ pubsub1id }}"
        instance_tags:
          Name: "Bastion host"
          Project: "VProfile"
        exact_count: 1
        count_tag:
          Name: "Bastion host"
          Project: "VProfile"
        group_id: "{{bastionSG_out.group_id}}"
      register: bastionHost_out

    - debug:
        var: bastionHost_out
