---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: import VPC setup variables
      include_vars: vars/output_vars

    - name: import stack-setup variables
      include_vars: vars/vpro_stack_setup

    - name: create a new ec2 key pair, returns generated private key
      amazon.aws.ec2_key:
        name: vpro_keypair
        region: "{{region}}"
      register: vprokey_out

    - name: save private key into vpro_loginkey.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./vpro_loginkey.pem"
        mode: 0600
      when: vprokey_out.changed